[package]
name = "aamp"
description = "Rust library for Nintendo parameter archive (AAMP) files"
homepage = "https://github.com/NiceneNerd/aamp-rust"
readme = "README.md"
keywords = ["Nintendo", "aamp", "Zelda", "gamedev"]
categories = ["game-development", "parsing"]
version = "0.1.0"
authors = ["Caleb Smith <macadamiadaze@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
binread = "1.0.0"
binwrite = "0.2.1"
cached = "0.13.1"
crc = "1.8.1"
indexmap = "1.4.0"
glob = "0.3.0"
lazy_static = "1.4.0"
libyaml = "0.1.0"
unescape = "0.1.0"
